// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID           string     `json:"id"`
	PostID       string     `json:"postID"`
	ParentID     *string    `json:"parentID,omitempty"`
	Content      string     `json:"content"`
	AuthorID     string     `json:"authorID"`
	CreatedAt    string     `json:"createdAt"`
	UpdatedAt    string     `json:"updatedAt"`
	Replies      []*Comment `json:"replies,omitempty"`
	RepliesCount *int       `json:"repliesCount,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
	Content  string  `json:"content"`
	AuthorID string  `json:"authorID"`
}

type NewPost struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	AuthorID      string `json:"authorID"`
	AllowComments bool   `json:"allowComments"`
}

type Post struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	AuthorID      string `json:"authorID"`
	AllowComments bool   `json:"allowComments"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type Query struct {
}
